### ISSUE TITLE
Expand button missing in Firefox

### ISSUE THREAD

**Issue by lassebenni** [getlinksc/css-selector-tool#1]
Hi, love your idea for a web based scraper!

Unfortunately on Firefox (123.0 (64-bit)) I am missing the "expand" button to be able to expand the webpage and work with it:

<img width="721" alt="image" src="https://github.com/getlinksc/css-selector-tool/assets/7990862/abe42c6d-b0d6-46f3-a739-6d9edabdd622">
I tested it on Chrome, it works there.

Sidenote: How do I "export" the results from the application once its found?

**Comment by getlinksc** [comment]
Appreciate you reporting this. I'll take a look into a fix for Firefox.

Exporting the data should be easy. I can see if I can add an button to export the JSON data.

**Comment by getlinksc** [comment]
- Default iframe size for Firefox to 850x620
- Added export function

![image](https://github.com/getlinksc/css-selector-tool/assets/58829603/e8987bdc-863a-4251-9d08-2f0556088dec)
