### ISSUE TITLE
Feature request: Possibility to delete a selector?

### ISSUE THREAD

**Issue by AnabasisXu** [getlinksc/css-selector-tool#5]
On the `Parse for select selector` interface, I can add selectors. But when I need to remove a selector, there seems to be no `delete` option?

**Comment by getlinksc** [comment]
The quickest way is to reuse the old selector you don't need. Or refresh the page.

I've tried adding a remove selector before but my UI experience is limited and didn't look good. Will try again and see what I can do

**Comment by AnabasisXu** [comment]
@getlinksc Thank you! `reuse the old selector` works fine.
